- name: "Accessories"
  description: "Accessories"
  packages:
    - cheese
    - font-manager-git
    - galculator
    - gpick
    - flameshot-git
    - liferea
    - mediainfo-gui
    - mcomix
    - nitrogen
    - nomacs
    - pdfarranger
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - vim-plugins
- name: "Git"
  description: "Git applications"
  packages:
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Password Manager"
  description: "Password managers"
  packages:
    - bitwarden
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "Vmware"
  description: "Installs vmware software"
  packages:
    - open-vm-tools
    - vmware-workstation
    - vmware-keymaps
